## YAML Template.
---
ldap:
  bind-url: 
  bind-username: 
  bind-password: 
  base-dn: 
  user-dn-pattern: 
  search-user-filter-pattern: "(&(sAMAccountName={0})(objectClass=Person))"
  user-username-attribute: "sAMAccountName"
  user-fullname-attribute: "displayName"
  user-email-attribute: "mail"
  user-groups-attribute: "memberOf"
  user-group-name-pattern: "CN=(?<groupName>[^,]+)"
  group-search-base: 
